service:
  name: reviews
  port: 8082
  logLevel: debug

upstreamServices:
  ratings:
    endpoints: ratings.default.svc.cluster.local:8083
    enableXDS: true

image: cr-cn-beijing.volces.com/coa-samples/bookinfo