apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: {{ .Values.service.name }}
    app.kubernetes.io/name: {{ .Values.service.name }}
  name: {{ .Values.service.name }}-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Values.service.name }}
      app.kubernetes.io/name: {{ .Values.service.name }}
      version: v2
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
        checksum/config: {{ include (print $.Template.BasePath "/reviews.cm.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/instance: {{ .Values.service.name }}
        app.kubernetes.io/name: {{ .Values.service.name }}
        version: v2
    spec:
      containers:
        - args:
            - {{ .Values.service.name }}
            - --config=config/{{ .Values.service.name }}.yaml
          env:
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: service.version=v2
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: {{ .Values.global.otel.endpoint }}
            - name: ENABLE_RATINGS
              value: "enable"
            - name: TZ
              value: Asia/Shanghai
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: INSTANCE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: METRICS_LOG_LEVEL
              value: err
            - name: CONSUL_HTTP_HOST
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: status.hostIP
            - name: ISTIO_META_CLUSTER_ID
              value: {{ .Values.global.multiCluster.clusterName }}
          image: {{ .Values.global.image }}
          imagePullPolicy: Always
          name: server
          ports:
          - containerPort: {{ .Values.service.port }}
            protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 128Mi
          volumeMounts:
            - mountPath: /app/config
              name: config-volume
      restartPolicy: Always
      serviceAccountName: default
      volumes:
        - configMap:
            defaultMode: 420
            name: {{ .Values.service.name }}
          name: config-volume

