global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "consul"
    consul_sd_configs:
      - server: consul:8500
        services:
          - prometheus
    relabel_configs:
      - source_labels: [ __meta_consul_tags ]
        action: replace
        target_label: service
        regex: ".*service:(.*?),.*"
        replacement: "$1"

      - source_labels: [ __meta_consul_service_id ]
        target_label: __metrics_path__
        replacement: /metrics
